### ISSUE TITLE
Forget nodes does not remove them from all proposals

### ISSUE THREAD

**Issue by tpatzig** [sap-oc/crowbar-core#33] opened 2017-06-02 05:32 UTC
We forgot nodes, that were in state 'Discovered' and they were still in the network proposal, which prevents us loading the proposal from file, without removing them one by one, reported from the error log.

**Comment by vuntz** [comment] 2017-06-02 05:34
Duplicate of https://github.com/sap-oc/crowbar-core/issues/8, which links to a patch.

**Closed as completed by vuntz** 2017-06-02 05:34 UTC
